expensemanager/urls.py
from django.urls import path
from . import views

app_name = 'expensemanager'
urlpatterns = [
    path('expense-home/', views.expenseHome, name='expense-home')
]

jobtracker/urls.py
from django.urls import path
from . import views

app_name = 'jobtracker'
urlpatterns = [
    path('job-home/', views.jobTracker, name='job-home'),
]

todoapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home-page'),
    path('register/', views.register, name='register' ),
    path('login/', views.loginPage, name='login-page'),
    path('logout/', views.logoutUser, name='logout'),
    path('delete-task/<str:name>/', views.deleteTask, name='delete-task'),
    path('update-status/<str:name>/', views.updateStatus, name='update-status'),
]

todoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
    path('', include('expensemanager.urls')),
    path('', include('jobtracker.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

expensemanager/models.py
from django.db import models

# Create your models here.

jobtracker/models.py
from django.db import models

# Create your models here.

todoapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

PRIORITY_CHOICES = [
        ('High Priority', 'High Priority'),
        ('Medium Priority', 'Medium Priority'),
        ('Low Priority', 'Low Priority'),
    ]

class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    todo_name = models.CharField(max_length=500)
    priority = models.CharField(max_length=100, choices=PRIORITY_CHOICES)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_name
# Create your models here.

expensemanager/views.py
from django.shortcuts import render

# Create your views here.

def expenseHome(request):
    return render(request, 'expensemanager/expense-home.html')

jobtracker/views.py
from django.shortcuts import render

# Create your views here.

def jobTracker(request):
    return render(request, 'jobtracker/job-home.html')

todoapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Todo
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def home(request):
    if request.method == 'POST':
        task_name = request.POST.get('task_name')
        priority = request.POST.get('priority')
        new_todo = Todo(user=request.user, todo_name=task_name, priority=priority)
        new_todo.save()

    in_progress_count = Todo.objects.filter(user=request.user, status=False).count()

    all_todos = Todo.objects.filter(user=request.user)

    search_query = request.GET.get('search')
    if search_query:
        all_todos = all_todos.filter(todo_name__icontains=search_query)

    context = {
        'todos': all_todos,
        'in_progress_count': in_progress_count
    }
        
    return render(request, 'todoapp/index.html', context)

def register(request):
    if request.user.is_authenticated:
        return redirect('home-page')
    if request.method =='POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        if len(password) < 8:
            messages.error(request, 'Password must be atleast 8 characters')
            return redirect('register')
        
        get_allUsers_by_username = User.objects.filter(username=username)
        if get_allUsers_by_username:
            messages.error(request, 'Username already exist, try another.')
            return redirect('register')

        new_user = User.objects.create_user(username=username, email=email, password=password)
        new_user.save()
        messages.success(request, 'User successfully created, LOGIN now')
        return redirect('login-page')

    return render(request, 'todoapp/register.html')

def logoutUser(request):
    logout(request)
    return redirect('login-page')

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('home-page')
    if request.method == 'POST':
        username = request.POST.get('user_name')
        password = request.POST.get('pass_word')

        validate_user = authenticate(username=username, password=password)
        if validate_user is not None:
            login(request, validate_user)
            return redirect('home-page')
        else:
            messages.error(request, 'please check username & password or User does not exist')
            return redirect('login-page')

    return render(request, 'todoapp/login.html')

@login_required
def deleteTask(request, name):
    delete_todo = Todo.objects.filter(user=request.user, todo_name=name)
    delete_todo.delete()
    return redirect('home-page')

@login_required
def updateStatus(request, name):
    get_todo = Todo.objects.get(user=request.user, todo_name=name)
    get_todo.status = True
    get_todo.save()
    return redirect('home-page')

expensemanager/templates/expensemanager/expense-home.html
<h1>Coming soon...</h1>

jobtracker/templates/jobtracker/job-home.html
<h2>Coming soon...</h2>

todoapp/templates/todoapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trifecta</title>
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <section class="header">
        <div class="logo">
            <a href="">Trifecta</a>
        </div>

        <div class="nav-btn">
            <a href="{% url 'home-page' %}"><button>To-do list</button></a>
            <a href="{% url 'expensemanager:expense-home' %}"><button> Expense Manager</button></a>
            <a href="{% url 'jobtracker:job-home' %}"><button>Job tracker</button></a>
        </div>

        <div class="logout">
            <a href="{% url 'logout' %}">Logout</a>
        </div>
        
    </section>

    <section class="task-container">
        <div class="username">
            <h1>Hello <span>{{user}},</span></h1>
            <h2>You have {{ in_progress_count }} incomplete task{{ in_progress_count|pluralize }}</h2>
            <!-- <h2>You have 1 incomplete task</h2> -->

        </div>
    </section>

    <section class="search-box">
        <div class="search">
            <form method="GET" action="{% url 'home-page' %}">
                <input type="text" name="search" placeholder="Search the task...">
                <button type="submit">Search</button>
            </form>
            <!-- <input type="text" placeholder="Search the task...">
            <button>Search</button> -->
        </div>
    </section>

    <section class="list-area">

        <div class="task-list">
            <table class="title">
                <tr>
                    <th>Tasks</th>
                    <th>Priority</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
                {% for todo in todos|slice:":8" %}
                <tr>
                    <td>{{todo.todo_name}}</td>

                    {% if todo.priority == 'High Priority' %}
                    <td style="color: red;">{{todo.priority}}</td>
                    {% elif todo.priority == 'Medium Priority' %}
                    <td style="color: yellow;">{{todo.priority}}</td>
                    {% elif todo.priority == 'Low Priority' %}
                    <td style="color: green;">{{todo.priority}}</td>
                    {% endif %}

                    {% if todo.status == True %}
                        <td style="color: green;">Completed</td>
                    {% else %}
                        <td>In progress</td>
                    {% endif %}

                    <td>
                        <a href="{% url 'update-status' todo.todo_name %}"><button type="submit"><i class='bx bx-check'></i></button></a>
                        <a href="{% url 'delete-task' todo.todo_name %}"><button type="submit"><i class='bx bxs-trash'></i></button></a>
                    </td>
                </tr>
                {% endfor %}
                
            </table>
        </div>

        <div class="add-task">
            <form method="POST" class="add" action="">
                {% csrf_token %}
                <label class="task-name">Task name</label>
                <input type="text" name="task_name">
                <label for="priority" class="task-name">Priority</label>
                <select id="priority" name="priority">
                    <option value="Priority">Select</option>
                    <option style="color: red;" value="High Priority">High Priority</option>
                    <option style="color: yellow;" value="Medium Priority">Medium Priority</option>
                    <option style="color: green;" value="Low Priority">Low Priority</option>
                </select>
                <button type="submit" >Add Task</button>
            </form>

        </div>

    </section>
</body>
</html>

todoapp/templates/todoapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'styles/login-register.css' %}">
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
</head>
<body>
    <section class="header">
            <div class="logo">
                <a href="">Trifecta</a>
            </div>

            <div class="nav-btn">
                <a href="{% url 'home-page' %}"><button>To-do list</button></a>
                <a href=""><button> Expense Manager</button></a>
                <a href=""><button>Job tracker</button></a>
            </div>

    </section>
    
    <section class="login-box">
            
        <form action="" method="POST">
            {% csrf_token %}
            <h1>Login</h1>
            {% if messages %}
                {% for message in messages %}
                <h2 style="color: red;">{{message}}</h2>
                {% endfor %}
            {% endif %}
            <label>Username:</label>
            <input type="text" required name="user_name">
            <label>Password:</label>
            <input type="password" required name="pass_word">
            <input class="button" type="submit" value="Login">
            <!-- <h3><a href="">Forget password !</a></h3> -->
            <h2>Don't have an account? <a href="{% url 'register' %}">Register Now</a></h2>
            
        </form>

    </section>
</body>
</html>

todoapp/templates/todoapp/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'styles/login-register.css' %}">
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
</head>
<body>
    <section class="header">
            <div class="logo">
                <a href="">Trifecta</a>
            </div>

            <div class="nav-btn">
                <a href="{% url 'home-page' %}"><button>To-do list</button></a>
                <a href=""><button> Expense Manager</button></a>
                <a href=""><button>Job tracker</button></a>
            </div>
            
    </section>
    
    <section class="login-box">
            
        <form action="" method="POST">
            {% csrf_token %}
            <h1>Register</h1><br>
            {% if messages %}
                {% for message in messages %}
                <h2 style="color: red;">{{message}}</h2>
                {% endfor %}
            {% endif %}
            <label>Username:</label>
            <input type="text" required name="username">
            <label>Email:</label>
            <input type="email" required name="email">
            <label>Password:</label>
            <input type="password" required name="password">
            <input class="button" type="submit" value="Login">
            <h2 class="login">Already have an account? <a href="{% url 'login-page' %}">Login</a></h2>
        </form>

    </section>
    
</body>
</html>